# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2.xci
# IP: The module: 'system_axi_gpio_2_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2.xci
# IP: The module: 'system_axi_gpio_2_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/gokul/playground/xilinx/del/lab2b/lab2b_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_2_2/system_axi_gpio_2_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
